import { describe, it, expect } from 'vitest';
import countriesReducer from './countriesSlice';

describe('countriesSlice', () => {
  it('should return the initial state', () => {
    const initialState = {
      list: [
        'Afganistan',
        'Albania',
        'Algieria',
        'Andora',
        'Angola',
        'Antigua i Barbuda',
        'Argentyna',
        'Armenia',
        'Australia',
        'Austria',
        'Azerbejdżan',
        'Bahamy',
        'Bahrajn',
        'Bangladesz',
        'Barbados',
        'Białoruś',
        'Belgia',
        'Belize',
        'Benin',
        'Bhutan',
        'Boliwia',
        'Bośnia i Hercegowina',
        'Botswana',
        'Brazylia',
        'Brunei',
        'Bułgaria',
        'Burkina Faso',
        'Burundi',
        'Republika Zielonego Przylądka',
        'Kambodża',
        'Kamerun',
        'Kanada',
        'Republika Środkowoafrykańska',
        'Czad',
        'Chile',
        'Chiny',
        'Kolumbia',
        'Komory',
        'Kongo',
        'Kostaryka',
        'Chorwacja',
        'Kuba',
        'Cypr',
        'Czechy',
        'Dania',
        'Dżibuti',
        'Dominika',
        'Dominikana',
        'Ekwador',
        'Egipt',
        'Salwador',
        'Gwinea Równikowa',
        'Erytrea',
        'Estonia',
        'Eswatini',
        'Etiopia',
        'Fidżi',
        'Finlandia',
        'Francja',
        'Gabon',
        'Gambia',
        'Gruzja',
        'Niemcy',
        'Ghana',
        'Grecja',
        'Grenada',
        'Gwatemala',
        'Gwinea',
        'Gwinea Bissau',
        'Gujana',
        'Haiti',
        'Honduras',
        'Węgry',
        'Islandia',
        'Indie',
        'Indonezja',
        'Iran',
        'Irak',
        'Irlandia',
        'Izrael',
        'Włochy',
        'Jamajka',
        'Japonia',
        'Jordania',
        'Kazachstan',
        'Kenia',
        'Kiribati',
        'Korea Północna',
        'Korea Południowa',
        'Kosowo',
        'Kuwejt',
        'Kirgistan',
        'Laos',
        'Łotwa',
        'Liban',
        'Lesotho',
        'Liberia',
        'Libia',
        'Liechtenstein',
        'Litwa',
        'Luksemburg',
        'Madagaskar',
        'Malawi',
        'Malezja',
        'Malediwy',
        'Mali',
        'Malta',
        'Wyspy Marshalla',
        'Mauretania',
        'Mauritius',
        'Meksyk',
        'Mikronezja',
        'Mołdawia',
        'Monako',
        'Mongolia',
        'Czarnogóra',
        'Maroko',
        'Mozambik',
        'Mjanma',
        'Namibia',
        'Nauru',
        'Nepal',
        'Holandia',
        'Nowa Zelandia',
        'Nikaragua',
        'Niger',
        'Nigeria',
        'Macedonia Północna',
        'Norwegia',
        'Oman',
        'Pakistan',
        'Palau',
        'Palestyna',
        'Panama',
        'Papua-Nowa Gwinea',
        'Paragwaj',
        'Peru',
        'Filipiny',
        'Polska',
        'Portugalia',
        'Katar',
        'Rumunia',
        'Rosja',
        'Rwanda',
        'Saint Kitts i Nevis',
        'Saint Lucia',
        'Saint Vincent i Grenadyny',
        'Samoa',
        'San Marino',
        'Wyspy Świętego Tomasza i Książęca',
        'Arabia Saudyjska',
        'Senegal',
        'Serbia',
        'Seszele',
        'Sierra Leone',
        'Singapur',
        'Słowacja',
        'Słowenia',
        'Wyspy Salomona',
        'Somalia',
        'Republika Południowej Afryki',
        'Sudan Południowy',
        'Hiszpania',
        'Sri Lanka',
        'Sudan',
        'Surinam',
        'Szwecja',
        'Szwajcaria',
        'Syria',
        'Tajwan',
        'Tadżykistan',
        'Tanzania',
        'Tajlandia',
        'Timor Wschodni',
        'Togo',
        'Tonga',
        'Trynidad i Tobago',
        'Tunezja',
        'Turcja',
        'Turkmenistan',
        'Tuvalu',
        'Uganda',
        'Ukraina',
        'Zjednoczone Emiraty Arabskie',
        'Wielka Brytania',
        'Stany Zjednoczone',
        'Urugwaj',
        'Uzbekistan',
        'Vanuatu',
        'Watykan',
        'Wenezuela',
        'Wietnam',
        'Jemen',
        'Zambia',
        'Zimbabwe',
      ],
    };
    expect(countriesReducer(undefined, { type: 'unknown' })).toEqual(initialState);
  });
});
